# -*- coding: utf-8 -*-
"""Geopy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nbCzvDGdrTbC_JI5lSd6WHgd2Sh14TPi
"""

pip install geopy

from geopy.geocoders import Nominatim
from geopy.exc import GeocoderTimedOut

def obter_cidade(latitude, longitude):
    # Configura o localizador com um nome de usuário (user_agent) obrigatório
    geolocator = Nominatim(user_agent="rastreador_cidades_v1")

    try:
        # Faz a busca reversa pelas coordenadas
        localizacao = geolocator.reverse((latitude, longitude), timeout=10)

        if localizacao:
            # Extrai os dados detalhados do endereço
            endereco = localizacao.raw.get('address', {})

            # Tenta buscar a cidade em diferentes campos comuns do retorno
            cidade = endereco.get('city') or endereco.get('town') or endereco.get('village') or endereco.get('municipality')
            estado = endereco.get('state')
            pais = endereco.get('country')

            return f"Cidade: {cidade} - {estado}, {pais}"
        else:
            return "Localização não encontrada."

    except GeocoderTimedOut:
        return "Erro: O serviço demorou muito para responder."

# Exemplo de uso (Coordenadas da Av. Paulista, São Paulo)
#lat = -23.5615
#lon = -46.6560
lat=-23.1694771
lon=-46.8992119

resultado = obter_cidade(lat, lon)
print(resultado)